package arte.entity;
// Generated 18 mar. 2019 16:48:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pintores generated by hbm2java
 */
public class Pintores  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private int edad;
     private Set pinturas = new HashSet(0);
     
     
    public Pintores() {
    }

	
    public Pintores(String nombre, String apellido, int edad) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
    }
    public Pintores(String nombre, String apellido, int edad, Set pinturas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.pinturas = pinturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public Set getPinturas() {
        return this.pinturas;
    }
    
    public void setPinturas(Set pinturas) {
        this.pinturas = pinturas;
    }




}


