package mp06.entity;
// Generated 6 mar. 2019 20:56:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Piloto generated by hbm2java
 */
public class Piloto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set mantenimientos = new HashSet(0);

    public Piloto() {
    }

	
    public Piloto(String nombre) {
        this.nombre = nombre;
    }
    public Piloto(String nombre, Set mantenimientos) {
       this.nombre = nombre;
       this.mantenimientos = mantenimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }




}


