package mp06.entity;
// Generated 6 mar. 2019 20:56:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculos generated by hbm2java
 */
public class Vehiculos  implements java.io.Serializable {


     private Integer id;
     private Modelo modelo;
     private String numeroPlaca;
     private Date fechaRegistro;
     private Set mantenimientos = new HashSet(0);

    public Vehiculos() {
    }

	
    public Vehiculos(Modelo modelo, String numeroPlaca, Date fechaRegistro) {
        this.modelo = modelo;
        this.numeroPlaca = numeroPlaca;
        this.fechaRegistro = fechaRegistro;
    }
    public Vehiculos(Modelo modelo, String numeroPlaca, Date fechaRegistro, Set mantenimientos) {
       this.modelo = modelo;
       this.numeroPlaca = numeroPlaca;
       this.fechaRegistro = fechaRegistro;
       this.mantenimientos = mantenimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getNumeroPlaca() {
        return this.numeroPlaca;
    }
    
    public void setNumeroPlaca(String numeroPlaca) {
        this.numeroPlaca = numeroPlaca;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }

    @Override
    public String toString() {
        return "Vehiculos{" + "\n\tid=" + id + ",\n\tmodelo=" + modelo + ",\n\tnumeroPlaca=" + numeroPlaca + ",\n\tfechaRegistro=" + fechaRegistro + ",\n\tmantenimientos=" + mantenimientos + '}';
    }




}


